-- Seed Data for Countries
INSERT INTO "countries" ("iso_a_2", "iso_a_3", "name") VALUES
('WW', 'WWW', 'Global'),
('AI', 'AIA', 'Anguilla'),
('GT', 'GTM', 'Guatemala'),
('GM', 'GMB', 'Gambia'),
('MX', 'MEX', 'Mexico'),
('MW', 'MWI', 'Malawi'),
('PN', 'PCN', 'Pitcairn Islands'),
('AR', 'ARG', 'Argentina'),
('GU', 'GUM', 'Guam'),
('BG', 'BGR', 'Bulgaria'),
('DM', 'DMA', 'Dominica'),
('GB', 'GBR', 'United Kingdom'),
('FM', 'FSM', 'Micronesia'),
('PS', 'PSE', 'Palestine'),
('CW', 'CUW', 'Curaçao'),
('RW', 'RWA', 'Rwanda'),
('HK', 'HKG', 'Hong Kong'),
('UZ', 'UZB', 'Uzbekistan'),
('CN', 'CHN', 'China'),
('CY', 'CYP', 'Cyprus'),
('AW', 'ABW', 'Aruba'),
('RE', 'REU', 'Réunion'),
('KR', 'KOR', 'South Korea'),
('AQ', 'ATA', 'Antarctica'),
('SO', 'SOM', 'Somalia'),
('LB', 'LBN', 'Lebanon'),
('GN', 'GIN', 'Guinea'),
('TJ', 'TJK', 'Tajikistan'),
('MY', 'MYS', 'Malaysia'),
('KP', 'PRK', 'North Korea'),
('SL', 'SLE', 'Sierra Leone'),
('BJ', 'BEN', 'Benin'),
('IT', 'ITA', 'Italy'),
('TT', 'TTO', 'Trinidad and Tobago'),
('SA', 'SAU', 'Saudi Arabia'),
('CR', 'CRI', 'Costa Rica'),
('RS', 'SRB', 'Serbia'),
('TK', 'TKL', 'Tokelau'),
('MN', 'MNG', 'Mongolia'),
('BN', 'BRN', 'Brunei'),
('HU', 'HUN', 'Hungary'),
('MZ', 'MOZ', 'Mozambique'),
('KI', 'KIR', 'Kiribati'),
('HT', 'HTI', 'Haiti'),
('KH', 'KHM', 'Cambodia'),
('EG', 'EGY', 'Egypt'),
('TM', 'TKM', 'Turkmenistan'),
('OM', 'OMN', 'Oman'),
('JM', 'JAM', 'Jamaica'),
('AZ', 'AZE', 'Azerbaijan'),
('SK', 'SVK', 'Slovakia'),
('BY', 'BLR', 'Belarus'),
('VN', 'VNM', 'Vietnam'),
('VI', 'VIR', 'United States Virgin Islands'),
('GI', 'GIB', 'Gibraltar'),
('SX', 'SXM', 'Sint Maarten'),
('AX', 'ALA', 'Åland Islands'),
('SY', 'SYR', 'Syria'),
('MQ', 'MTQ', 'Martinique'),
('GL', 'GRL', 'Greenland'),
('HN', 'HND', 'Honduras'),
('TN', 'TUN', 'Tunisia'),
('KM', 'COM', 'Comoros'),
('SI', 'SVN', 'Slovenia'),
('CH', 'CHE', 'Switzerland'),
('GG', 'GGY', 'Guernsey'),
('MM', 'MMR', 'Myanmar'),
('PY', 'PRY', 'Paraguay'),
('BQ', 'BES', 'Caribbean Netherlands'),
('BB', 'BRB', 'Barbados'),
('MO', 'MAC', 'Macau'),
('JO', 'JOR', 'Jordan'),
('LA', 'LAO', 'Laos'),
('TG', 'TGO', 'Togo'),
('MA', 'MAR', 'Morocco'),
('PR', 'PRI', 'Puerto Rico'),
('GF', 'GUF', 'French Guiana'),
('PM', 'SPM', 'Saint Pierre and Miquelon'),
('MF', 'MAF', 'Saint Martin'),
('EE', 'EST', 'Estonia'),
('ID', 'IDN', 'Indonesia'),
('SC', 'SYC', 'Seychelles'),
('ML', 'MLI', 'Mali'),
('TL', 'TLS', 'Timor-Leste'),
('BR', 'BRA', 'Brazil'),
('GH', 'GHA', 'Ghana'),
('KE', 'KEN', 'Kenya'),
('IS', 'ISL', 'Iceland'),
('MG', 'MDG', 'Madagascar'),
('BD', 'BGD', 'Bangladesh'),
('CD', 'COD', 'DR Congo'),
('ZW', 'ZWE', 'Zimbabwe'),
('PF', 'PYF', 'French Polynesia'),
('TR', 'TUR', 'Turkey'),
('CV', 'CPV', 'Cape Verde'),
('DO', 'DOM', 'Dominican Republic'),
('BS', 'BHS', 'Bahamas'),
('DE', 'DEU', 'Germany'),
('SR', 'SUR', 'Suriname'),
('TO', 'TON', 'Tonga'),
('IO', 'IOT', 'British Indian Ocean Territory'),
('LC', 'LCA', 'Saint Lucia'),
('IE', 'IRL', 'Ireland'),
('VA', 'VAT', 'Vatican City'),
('CO', 'COL', 'Colombia'),
('PT', 'PRT', 'Portugal'),
('FO', 'FRO', 'Faroe Islands'),
('ST', 'STP', 'São Tomé and Príncipe'),
('MP', 'MNP', 'Northern Mariana Islands'),
('JE', 'JEY', 'Jersey'),
('YT', 'MYT', 'Mayotte'),
('YE', 'YEM', 'Yemen'),
('NG', 'NGA', 'Nigeria'),
('AF', 'AFG', 'Afghanistan'),
('BW', 'BWA', 'Botswana'),
('IM', 'IMN', 'Isle of Man'),
('SV', 'SLV', 'El Salvador'),
('UG', 'UGA', 'Uganda'),
('AD', 'AND', 'Andorra'),
('TC', 'TCA', 'Turks and Caicos Islands'),
('TD', 'TCD', 'Chad'),
('FI', 'FIN', 'Finland'),
('RU', 'RUS', 'Russia'),
('KZ', 'KAZ', 'Kazakhstan'),
('SJ', 'SJM', 'Svalbard and Jan Mayen'),
('VE', 'VEN', 'Venezuela'),
('MC', 'MCO', 'Monaco'),
('SN', 'SEN', 'Senegal'),
('NP', 'NPL', 'Nepal'),
('AE', 'ARE', 'United Arab Emirates'),
('TW', 'TWN', 'Taiwan'),
('NC', 'NCL', 'New Caledonia'),
('BO', 'BOL', 'Bolivia'),
('CL', 'CHL', 'Chile'),
('CI', 'CIV', 'Ivory Coast'),
('LY', 'LBY', 'Libya'),
('PE', 'PER', 'Peru'),
('CA', 'CAN', 'Canada'),
('FR', 'FRA', 'France'),
('DJ', 'DJI', 'Djibouti'),
('BI', 'BDI', 'Burundi'),
('XK', 'UNK', 'Kosovo'),
('DK', 'DNK', 'Denmark'),
('GR', 'GRC', 'Greece'),
('CZ', 'CZE', 'Czechia'),
('ER', 'ERI', 'Eritrea'),
('NA', 'NAM', 'Namibia'),
('VG', 'VGB', 'British Virgin Islands'),
('IR', 'IRN', 'Iran'),
('GQ', 'GNQ', 'Equatorial Guinea'),
('MR', 'MRT', 'Mauritania'),
('BH', 'BHR', 'Bahrain'),
('CC', 'CCK', 'Cocos (Keeling) Islands'),
('ET', 'ETH', 'Ethiopia'),
('ZM', 'ZMB', 'Zambia'),
('BA', 'BIH', 'Bosnia and Herzegovina'),
('FK', 'FLK', 'Falkland Islands'),
('GD', 'GRD', 'Grenada'),
('TH', 'THA', 'Thailand'),
('RO', 'ROU', 'Romania'),
('VC', 'VCT', 'Saint Vincent and the Grenadines'),
('LR', 'LBR', 'Liberia'),
('US', 'USA', 'United States'),
('SS', 'SSD', 'South Sudan'),
('BV', 'BVT', 'Bouvet Island'),
('AM', 'ARM', 'Armenia'),
('JP', 'JPN', 'Japan'),
('PK', 'PAK', 'Pakistan'),
('SZ', 'SWZ', 'Eswatini'),
('LI', 'LIE', 'Liechtenstein'),
('IL', 'ISR', 'Israel'),
('AS', 'ASM', 'American Samoa'),
('LK', 'LKA', 'Sri Lanka'),
('GS', 'SGS', 'South Georgia'),
('AL', 'ALB', 'Albania'),
('DZ', 'DZA', 'Algeria'),
('UA', 'UKR', 'Ukraine'),
('SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha'),
('HM', 'HMD', 'Heard Island and McDonald Islands'),
('SM', 'SMR', 'San Marino'),
('CU', 'CUB', 'Cuba'),
('NR', 'NRU', 'Nauru'),
('ES', 'ESP', 'Spain'),
('KW', 'KWT', 'Kuwait'),
('MS', 'MSR', 'Montserrat'),
('MU', 'MUS', 'Mauritius'),
('SE', 'SWE', 'Sweden'),
('AU', 'AUS', 'Australia'),
('CM', 'CMR', 'Cameroon'),
('EC', 'ECU', 'Ecuador'),
('QA', 'QAT', 'Qatar'),
('MH', 'MHL', 'Marshall Islands'),
('PL', 'POL', 'Poland'),
('KY', 'CYM', 'Cayman Islands'),
('ZA', 'ZAF', 'South Africa'),
('WF', 'WLF', 'Wallis and Futuna'),
('WS', 'WSM', 'Samoa'),
('NL', 'NLD', 'Netherlands'),
('EH', 'ESH', 'Western Sahara'),
('ME', 'MNE', 'Montenegro'),
('BT', 'BTN', 'Bhutan'),
('MT', 'MLT', 'Malta'),
('VU', 'VUT', 'Vanuatu'),
('TZ', 'TZA', 'Tanzania'),
('NZ', 'NZL', 'New Zealand'),
('PW', 'PLW', 'Palau'),
('PA', 'PAN', 'Panama'),
('TV', 'TUV', 'Tuvalu'),
('FJ', 'FJI', 'Fiji'),
('NI', 'NIC', 'Nicaragua'),
('KG', 'KGZ', 'Kyrgyzstan'),
('TF', 'ATF', 'French Southern and Antarctic Lands'),
('LV', 'LVA', 'Latvia'),
('GE', 'GEO', 'Georgia'),
('LU', 'LUX', 'Luxembourg'),
('AT', 'AUT', 'Austria'),
('MK', 'MKD', 'North Macedonia'),
('BL', 'BLM', 'Saint Barthélemy'),
('CX', 'CXR', 'Christmas Island'),
('SB', 'SLB', 'Solomon Islands'),
('AG', 'ATG', 'Antigua and Barbuda'),
('IQ', 'IRQ', 'Iraq'),
('MD', 'MDA', 'Moldova'),
('NF', 'NFK', 'Norfolk Island'),
('CG', 'COG', 'Republic of the Congo'),
('NU', 'NIU', 'Niue'),
('LT', 'LTU', 'Lithuania'),
('NE', 'NER', 'Niger'),
('GY', 'GUY', 'Guyana'),
('BM', 'BMU', 'Bermuda'),
('GA', 'GAB', 'Gabon'),
('CK', 'COK', 'Cook Islands'),
('AO', 'AGO', 'Angola'),
('NO', 'NOR', 'Norway'),
('GP', 'GLP', 'Guadeloupe'),
('MV', 'MDV', 'Maldives'),
('BE', 'BEL', 'Belgium'),
('HR', 'HRV', 'Croatia'),
('BZ', 'BLZ', 'Belize'),
('KN', 'KNA', 'Saint Kitts and Nevis'),
('SG', 'SGP', 'Singapore'),
('LS', 'LSO', 'Lesotho'),
('UY', 'URY', 'Uruguay'),
('BF', 'BFA', 'Burkina Faso'),
('IN', 'IND', 'India'),
('PH', 'PHL', 'Philippines'),
('CF', 'CAF', 'Central African Republic'),
('SD', 'SDN', 'Sudan'),
('GW', 'GNB', 'Guinea-Bissau'),
('PG', 'PNG', 'Papua New Guinea'),
('UM', 'UMI', 'United States Minor Outlying Islands')
ON CONFLICT DO NOTHING;
